steps:
- script: |
    export TF_VAR_project_name=${{parameters.TF_VAR_project_name}}
    export TF_VAR_app_name=${{parameters.TF_VAR_app_name}}
    export BRANCH_NAME=${{parameters.BRANCH_NAME}}
    export LIVEDIR=${{parameters.LIVEDIR}}
    export TF_VAR_region=${{parameters.TF_VAR_region}}

    echo LIVEDIR= $LIVEDIR
    echo TF_VAR_app_name=$TF_VAR_app_name
    
    echo "Create subfolder for $LIVEDIR and copy teraform files from live dir into it."
    echo " then substitute AWS_REGION, APP_NAME and ENVIRONMENT ( which is BRANCH_NAME) in backend.tf.tpl because terraform does not allow variables in backend.tf"
    echo "These terraform files hold the code for the resources you want to deploy."
    preps/prepare-files-folders.sh
  displayName: 'script-prepare-files-folders'    


# Here the backend ( S3  bucket for terraform .state file and dynamodb table ) will be created.
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'aws-AzureDevopsiamuser'
    regionName: 'us-east-1'
    stackName: '${{parameters.TF_VAR_app_name}}-${{parameters.BRANCH_NAME}}'
    templateSource: 'file'
    templateFile: 'preps/cloudformation/cfn-tfbackend.yml'
    templateParametersSource: 'inline'
    templateParameters: |
      - ParameterKey: ProjectName
        ParameterValue: ${{parameters.TF_VAR_project_name}}
      - ParameterKey: AppName
        ParameterValue: ${{parameters.TF_VAR_app_name}}
      - ParameterKey: Environment
        ParameterValue: ${{parameters.BRANCH_NAME}}
  displayName: 'Cloudformation-create-S3'    
